name: springbok_router
author: Christophe Hurpeau <christophe@hurpeau.com>
version: 0.3.0
homepage: https://github.com/christophehurpeau/dart-springbok_router
description: Springbok Router for Dart
documentation: https://github.com/christophehurpeau/dart-springbok_router/wiki
environment:
  sdk: '>=1.1.0 <2.0.0'
dependencies:
  unittest: '>=0.10.0 <0.11.0'
  yaml: '>=0.9.0 <0.10.0'
